Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -68,6 +68,18 @@ jobs:
           echo '##vso[task.setvariable variable=isMutexSet]true'
         name: 'Acquire_the_distributed_mutex'
       - script: |
+          # run unit test and build executable
+          # the set -e line is needed so that the unit tests failure would cause the job to fail properly
+          # set -e
+          # go test -race -short -cover ./cmd ./common ./ste ./azbfs
+          GOARCH=amd64 GOOS=linux go build -o azcopy_linux_amd64
+        name: 'Run_unit_tests'
+        env:
+          ACCOUNT_NAME: $(ACCOUNT_NAME)
+          ACCOUNT_KEY: $(ACCOUNT_KEY)
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
+      - script: |
           go build -o test-validator ./testSuite/
           mkdir test-temp
           export AZCOPY_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
